services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: banana
            MARIADB_DATABASE: minecraft
            MARIADB_USER: user
            MARIADB_PASSWORD: banana
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: banana
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    db_data:
    mongo_data: